### ISSUE TITLE
Could not import plugin: Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'data-uri-to-buffer'

### ISSUE THREAD

**Issue by FunctionDJ** [cdeleeuwe/netlify-plugin-submit-sitemap#26] opened 2022-04-08 21:28 UTC
Just got the above error when trying to deploy my site.
Here's the more detailed log from Netlify:
```
11:25:04 PM: ────────────────────────────────────────────────────────────────
11:25:04 PM:   Plugin "netlify-plugin-submit-sitemap" internal error         
11:25:04 PM: ────────────────────────────────────────────────────────────────
11:25:04 PM: ​
11:25:04 PM:   Error message
11:25:04 PM:   Could not import plugin:
11:25:04 PM:   Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'data-uri-to-buffer' imported from /opt/build/repo/node_modules/node-fetch/src/index.js
11:25:04 PM: ​
11:25:04 PM:   Plugin details
11:25:04 PM:   Package:        netlify-plugin-submit-sitemap
11:25:04 PM:   Version:        0.3.0
11:25:04 PM:   Repository:     git+https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap.git
11:25:04 PM:   npm link:       https://www.npmjs.com/package/netlify-plugin-submit-sitemap
11:25:04 PM:   Report issues:  https://github.com/cdeleeuwe/netlify-plugin-submit-sitemap/issues
11:25:04 PM: ​
11:25:04 PM:   Error location
11:25:04 PM:   While loading "netlify-plugin-submit-sitemap" from netlify.toml and package.json
11:25:04 PM:       at new NodeError (node:internal/errors:371:5)
11:25:04 PM:       at packageResolve (node:internal/modules/esm/resolve:932:9)
11:25:04 PM:       at moduleResolve (node:internal/modules/esm/resolve:978:18)
11:25:04 PM:       at defaultResolve (node:internal/modules/esm/resolve:1080:11)
11:25:04 PM:       at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
11:25:04 PM:       at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
11:25:04 PM:       at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
11:25:04 PM:       at link (node:internal/modules/esm/module_job:78:36)
11:25:04 PM: ​
11:25:04 PM:   Error properties
11:25:04 PM:   { code: 'ERR_MODULE_NOT_FOUND' }
11:25:04 PM: ​
11:25:04 PM:   Resolved config
11:25:04 PM:   build:
11:25:04 PM:     command: npm run build
11:25:04 PM:     commandOrigin: config
11:25:04 PM:     environment:
11:25:04 PM:       - GOOGLE_CLOUD_PLATFORM_API_KEY
11:25:04 PM:       - GOOGLE_SPREADSHEET_ID
11:25:04 PM:       - NODE_VERSION
11:25:04 PM:       - ONEGRAPH_AUTHLIFY_TOKEN
11:25:04 PM:     processing:
11:25:04 PM:       skip_processing: true
11:25:04 PM:     publish: /opt/build/repo/out
11:25:04 PM:     publishOrigin: config
11:25:04 PM:   functionsDirectory: /opt/build/repo/netlify/functions
11:25:04 PM:   plugins:
11:25:04 PM:     - inputs: {}
11:25:04 PM:       origin: config
11:25:04 PM:       package: '@netlify/plugin-lighthouse'
11:25:04 PM:     - inputs: {}
11:25:04 PM:       origin: config
11:25:04 PM:       package: netlify-plugin-submit-sitemap
```

**Comment by cdeleeuwe** [comment] 2022-04-18 15:01
@FunctionDJ I am not able to reproduce this issue. Did you already try clearing the build cache?

**Comment by cdeleeuwe** [comment] 2022-06-11 05:35
Closing this for now. If this is still an issue, let me know.

**Closed by cdeleeuwe** 2022-06-11 05:35 UTC
